config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :accounts do
    resources :transactions
  end

  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :transactions
  validates :bank_balance,
    :presence => true
  scope :get_names_not_closed, lambda {|account_id|
    where.not(id: account_id, closed: 1).collect {|p| [ p.name, p.id.to_i() ] }
  }
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account
  accepts_nested_attributes_for :account
  attr_accessor :password_confirmation, :transferred_account_object
  before_validation :calculate_rates_and_total
  before_create :set_bank_balance
  validate :password
  validate :does_not_have_transfer
  validate :does_not_have_funds
  validates_associated :account
  validates_numericality_of :transaction_value,
    :on => :create,
    :greater_than => 0,
    :message => 'deve ser maior que 0.'
  scope :created_between, lambda {|start_date, end_date|
    if start_date && end_date
      where(:created_at => Date.new(start_date[:year].to_i, start_date[:month].to_i, start_date[:day].to_i)..
            Date.new(end_date[:year].to_i, end_date[:month].to_i, end_date[:day].to_i))
    end
  }

  def password
    if !is_deposit
      errors[:base] << 'Senha não corresponde a do usuário da conta.' if self.password_confirmation != account.password
    end
  end

  def does_not_have_transfer
    if is_transfer
      errors[:base] << 'Você precisa escolher uma conta.' if !transferred_account
    end
  end

  def does_not_have_funds
    if !is_deposit
      errors[:base] <<  'Você não possui fundos suficientes.' if account.bank_balance < transaction_total
    end
  end

  def calculate_rates_and_total
    if !is_transfer
      self.transaction_rate = 0
      self.transaction_total = transaction_value
    else
      self.transaction_rate = calculate_rate
      self.transaction_total = transaction_value + transaction_rate + calculate_big_values_rate
    end
  end

  def calculate_rate
    _date = Time.now
    _week = _date.strftime('%w')
    _hour = _date.strftime('%T')
    _week != 0 and _week != 6 and _hour >= '09:00:00' and _hour < '18:00:00' ? 5 : 7
  end

  def calculate_big_values_rate
    transaction_value > 1000 ? 10 : 0
  end

  def set_bank_balance
    set_new_bank_balance_to_account_owner
    if is_transfer
      set_new_bank_balance_to_transferred_owner
    end
  end

  def set_new_bank_balance_to_account_owner
    self.account.bank_balance = is_deposit ? account.bank_balance + transaction_total : account.bank_balance - transaction_total
  end

  def set_new_bank_balance_to_transferred_owner
    self.transferred_account_object = Account.find(transferred_account)
    self.transferred_account_object.bank_balance = self.transferred_account_object.bank_balance + transaction_value
  end

  def is_transfer
    transaction_type == 3
  end

  def is_deposit
    transaction_type == 1
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :update_account_situation]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Conta criada com sucesso.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_url, notice: 'Conta atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    respond_to do |format|
      if @account.delete
      format.html { redirect_to accounts_url, notice: 'Conta não pode ser excluída.' }
      format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :password, :bank_balance, :closed)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Account.find(params[:account_id]).transactions.created_between(params[:created_at_gte], params[:created_at_lt])
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.account = Account.find(params[:account_id])
    respond_to do |format|
      if @transaction.save and @transaction.account.save and
          (!@transaction.transferred_account_object || @transaction.transferred_account_object.save)
        format.html { redirect_to @transaction.account, notice: 'Transação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transação alterada com sucesso' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transação excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.delete(:created_at_gte)
      params.delete(:created_at_lt)
      params.delete(:utf8)
      params.delete(:commit)
      params.delete(:authenticity_token)
      params.require(:transaction).permit(:transaction_type, :transaction_value, :transaction_rate, :transaction_total, :account_id, :transferred_account, :created_at, :password_confirmation)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def translate_transaction_type_helper(transaction_type)
    if transaction_type == 1
      'Depósito'
    elsif transaction_type == 2
      'Saque'
    elsif transaction_type == 3
      'Transferência'
    else
      ''
    end
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @account.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@account.errors.count, "error") %> <%= @transaction.errors.count > 1 ? 'proibiram' : 'proibiu' %> esta conta de ser salva:</h4>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label  :name, 'Nome', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, 'Senha', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :password, :type => "password", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bank_balance, 'Saldo Bancário', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :bank_balance, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :closed, 'Conta Fechada?', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :closed, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Salvar', :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
     Voltar
  <% end %>
  <%= link_to @account, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
     Mostrar
  <% end %>
  <h1>Editar Conta</h1>
</div>

<%= render 'form' %>

app/views/accounts/index.html.erb
<div class="page-header">
  <%= link_to new_account_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nova Conta
  <% end %>
  <h1>Listagem de Contas</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Saldo Bancário</th>
            <th>Escolha Conta</th>
            <th>Situação</th>
            <th>Edição</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @accounts) do |account| %>
            <td><%= account.name %></td>
            <td><%= number_to_currency(account.bank_balance, unit: 'R$', separator: ',', delimiter: '.') %></td>
            <% if account.closed %>
                <td>Não permitido</td>
                <td>Conta Encerrada</td>
            <% else %>
                <td><%= link_to 'Utilizar Conta', account %></td>
                <td>Conta Ativa</td>
            <% end %>
            <td><%= link_to 'Editar', edit_account_path(account) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Nova Conta</h1>
</div>

<%= render 'form' %>

app/views/accounts/show.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
     Voltar
  <% end %>
  <%= link_to edit_account_path(@account), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
     Editar
  <% end %>
  <h1>Conta Bancária</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @account.name %></dd>

  <dt>Saldo Bancário:</dt>
  <dd><%= number_to_currency(@account.bank_balance, unit: 'R$', separator: ',', delimiter: '.') %></dd>

  <dt>Situação da Conta:</dt>
  <dd><%= @account.closed ? 'Conta Encerrada' : 'Conta Ativa' %></dd>

</dl>
<%= link_to account_transactions_path(@account.id), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
  Extrato Bancário
<% end %> |
<%= link_to new_account_transaction_path(@account.id), :class => 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  Nova Transação Financeira
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Integra - Ruby on Rails</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Teste Integra", "/", :class => "navbar-brand" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == ":error" ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for([:account, @transaction], :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @transaction.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@transaction.errors.count, "erro") %> <%= @transaction.errors.count > 1 ? 'proibiram' : 'proibiu' %> esta transação de ser salva:</h4>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :transaction_type, 'Tipo de Transação', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:transaction_type, [[translate_transaction_type_helper(1), 1.to_i()], [translate_transaction_type_helper(2), 2.to_i()], [translate_transaction_type_helper(3), 3.to_i()]], {}, :class => "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :transaction_value, 'Valor', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :transaction_value, value:0, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group" id="transfer_select__form_group">
    <%= f.label :transferred_account, 'Conta para transferência', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:transferred_account, Account.get_names_not_closed(params[:account_id]), {prompt: 'Escolha a conta'}, :class => "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Salvar', :class => "btn btn-primary", data: { confirm: 'modal'} %>
    </div>
  </div>
    <div class="modal fade" id="confirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" style="z-index: 10000;">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Autenticação</h4>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group" style="margin-left: 15px !important; margin-right: 15px !important;">
                <label for="password" class="control-label">Digite a senha do usuário da conta:</label>
                <%= f.password_field :password_confirmation, :class => "form-control"  %>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-primary confirm">Confirmar</button>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="page-header">
  <%= link_to transactions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
     Voltar
  <% end %>
  <%= link_to @transaction, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
     Mostrar
  <% end %>
  <h1>Edição de Transação</h1>
</div>

<%= render 'form' %>

app/views/transactions/index.html.erb
<div class="page-header">
  <%= link_to account_path(params[:account_id]), :class => 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to new_account_transaction_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nova Transação
  <% end %>
  <h1>Extrato Bancário</h1>
</div>
<div>
  <%= form_for account_transactions_path, method: 'get' do %>
      <%= select_date params[:created_at_gte] ? Date.new(params[:created_at_gte][:year].to_i, params[:created_at_gte][:month].to_i, params[:created_at_gte][:day].to_i) : Date.today, {order: [:day, :month, :year],
          :use_month_names => [t(:jan), t(:feb), t(:mar), t(:apr), t(:may), t(:jun), t(:jul), t(:aug), t(:sep), t(:oct), t(:nov), t(:dec)],
          :prefix => :created_at_gte} %>
      <%= select_date  params[:created_at_lt] ? Date.new(params[:created_at_lt][:year].to_i, params[:created_at_lt][:month].to_i, params[:created_at_lt][:day].to_i) : Date.today, {order: [:day, :month, :year],
          :use_month_names => [t(:jan), t(:feb), t(:mar), t(:apr), t(:may), t(:jun), t(:jul), t(:aug), t(:sep), t(:oct), t(:nov), t(:dec)],
          :prefix => :created_at_lt} %>>
      <%= submit_tag "Filtrar", :class => 'btn btn-default' %>
  <% end %>
</div>
<br>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Tipo de Transação</th>
            <th>Valor de Transferência</th>
            <th>Taxa de Transferência</th>
            <th>Valor Total</th>
            <th>Conta Transferência</th>
            <th>Data da Transação</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @transactions) do |transaction| %>
            <td><%= translate_transaction_type_helper(transaction.transaction_type) %></td>
            <td><%= number_to_currency(transaction.transaction_value, unit: 'R$', separator: ',', delimiter: '.') %></td>
            <td><%= number_to_currency(transaction.transaction_rate, unit: 'R$', separator: ',', delimiter: '.') %></td>
            <td><%= number_to_currency(transaction.transaction_total, unit: 'R$', separator: ',', delimiter: '.') %></td>
            <td><%= transaction.transferred_account ? Account.find(transaction.transferred_account).name : 'Própria Conta' %></td>
            <td><%= transaction.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
            <td><%= link_to 'Mostrar', account_transaction_path(transaction.account,transaction) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="page-header">
  <%= link_to account_transactions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Nova Transação</h1>
</div>

<%= render 'form' %>

app/views/transactions/show.html.erb
<div class="page-header">
  <%= link_to account_transactions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
     Voltar
  <% end %>
  <h1>Transações</h1>
</div>

<dl class="dl-horizontal">
  <dt>Tipo de Transação:</dt>
  <dd><%= translate_transaction_type_helper(@transaction.transaction_type) %></dd>

  <dt>Valor de Transferência:</dt>
  <dd><%= number_to_currency(@transaction.transaction_value, unit: 'R$', separator: ',', delimiter: '.') %></dd>

  <dt>Taxa de Transferência:</dt>
  <dd><%= number_to_currency(@transaction.transaction_rate, unit: 'R$', separator: ',', delimiter: '.') %></dd>

  <dt>Valor Total:</dt>
  <dd><%= number_to_currency(@transaction.transaction_total, unit: 'R$', separator: ',', delimiter: '.') %></dd>

  <dt>Conta Transferência:</dt>
  <dd><%= @transaction.transferred_account ? Account.find(@transaction.transferred_account).name : 'Inexistente' %></dd>

</dl>